# Generated by Django 3.2 on 2022-12-30 14:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='شماره همراه')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام خانوادگی')),
                ('goal', models.CharField(max_length=2, verbose_name='هدف ثبت\u200cنام')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ثبت نام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_staff', models.BooleanField(default=False)),
                ('r_code', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=6)),
                ('r_code_time', models.DateTimeField(default=datetime.datetime(2022, 12, 30, 14, 15, 39, 266178, tzinfo=utc))),
                ('phone_valid', models.BooleanField(default=False, verbose_name='تایید شماره همراه')),
                ('security_code', models.CharField(blank=True, max_length=50, null=True)),
                ('register_complete', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربر ها',
                'ordering': ('-date_joined',),
            },
        ),
    ]
