# Generated by Django 3.2 on 2022-12-30 14:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='هدف ثبت\u200cنام'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='r_code_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 14, 35, 28, 375784, tzinfo=utc)),
        ),
    ]
