# Generated by Django 3.2 on 2022-12-31 07:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20221230_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='r_code_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 31, 7, 20, 51, 790105, tzinfo=utc)),
        ),
    ]
