# Generated by Django 3.2 on 2023-01-10 11:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userprofile_r_code_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='r_code_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 11, 35, 28, 144712, tzinfo=utc)),
        ),
    ]
