# Generated by Django 3.2 on 2022-12-30 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='شماره سوال')),
                ('question_type', models.CharField(choices=[('1', 'چند گزینه\u200cای'), ('2', 'متنی کوتاه\u200cپاسخ'), ('3', 'متنی بلند\u200cپاسخ'), ('4', 'عددی'), ('5', 'چند\u200cگزینه\u200cای (انتخاب چند گزینه همزمان)'), ('6', 'امتیازدهی (با ستاره)')], max_length=2, verbose_name='نوع سوال')),
                ('title', models.TextField(verbose_name='متن سوال')),
                ('subtitle', models.TextField(verbose_name='توضیحات سوال')),
                ('image', models.FileField(blank=True, null=True, upload_to='questions/files/', verbose_name='فایل سوال')),
                ('star_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد ستاره')),
            ],
            options={
                'verbose_name': 'پرسش\u200cنامه',
                'verbose_name_plural': 'پرسش\u200cنامه\u200cها',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='QuestionMultipleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='شماره گزینه')),
                ('text', models.CharField(max_length=255, verbose_name='متن گزینه')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choices', to='main.question', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'گزینه سوال چند گزینه\u200cای',
                'verbose_name_plural': 'گزینه\u200cهای سوال چند گزینه\u200cای',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ایجاد')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('text', models.TextField(verbose_name='توضیحات')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر سازنده')),
            ],
            options={
                'verbose_name': 'پرسش\u200cنامه',
                'verbose_name_plural': 'پرسش\u200cنامه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ایجاد')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.survey', verbose_name='پرسش\u200cنامه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='کاربر پاسخ\u200cدهنده')),
            ],
            options={
                'verbose_name': 'پاسخ پرسش\u200cنامه',
                'verbose_name_plural': 'پاسخ\u200cهای پرسش\u200cنامه',
            },
        ),
        migrations.CreateModel(
            name='QuestionStarAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.PositiveSmallIntegerField(verbose_name='پاسخ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_answers', to='main.question', verbose_name='سوال')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_answers', to='main.surveyanswer', verbose_name='پاسخ پرسش\u200cنامه')),
            ],
            options={
                'verbose_name': 'پاسخ سوال ستاره\u200cای',
                'verbose_name_plural': 'پاسخ\u200cهای سوال ستاره\u200cای',
            },
        ),
        migrations.CreateModel(
            name='QuestionShortAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255, verbose_name='پاسخ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_answer_answers', to='main.question', verbose_name='سوال')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_answer_answers', to='main.surveyanswer', verbose_name='پاسخ پرسش\u200cنامه')),
            ],
            options={
                'verbose_name': 'پاسخ سوال کوتاه\u200cپاسخ',
                'verbose_name_plural': 'پاسخ\u200cهای سوال کوتاه\u200cپاسخ',
            },
        ),
        migrations.CreateModel(
            name='QuestionNumberAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(verbose_name='پاسخ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_answers', to='main.question', verbose_name='سوال')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_answers', to='main.surveyanswer', verbose_name='پاسخ پرسش\u200cنامه')),
            ],
            options={
                'verbose_name': 'پاسخ سوال عددی',
                'verbose_name_plural': 'پاسخ\u200cهای سوال عددی',
            },
        ),
        migrations.CreateModel(
            name='QuestionMultipleChoiceAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice_answers', to='main.questionmultiplechoice', verbose_name='پاسخ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice_answers', to='main.question', verbose_name='سوال')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice_answers', to='main.surveyanswer', verbose_name='پاسخ پرسش\u200cنامه')),
            ],
            options={
                'verbose_name': 'پاسخ گزینه سوال چند گزینه\u200cای',
                'verbose_name_plural': 'پاسخ\u200cهای گزینه سوال چند گزینه\u200cای',
            },
        ),
        migrations.CreateModel(
            name='QuestionLongAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='long_answer_answers', to='main.question', verbose_name='سوال')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='long_answer_answers', to='main.surveyanswer', verbose_name='پاسخ پرسش\u200cنامه')),
            ],
            options={
                'verbose_name': 'پاسخ سوال بلند\u200cپاسخ',
                'verbose_name_plural': 'پاسخ\u200cهای سوال بلند\u200cپاسخ',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.survey', verbose_name='پرسش\u200cنامه'),
        ),
    ]
