# Generated by Django 3.2 on 2023-01-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ('-created',), 'verbose_name': 'پرسش\u200cنامه', 'verbose_name_plural': 'پرسش\u200cنامه\u200cها'},
        ),
        migrations.AlterField(
            model_name='question',
            name='subtitle',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات سوال'),
        ),
    ]
